export const ERROR = "ERROR";

// GUILDS
export const GET_GUILDS = "GET_GUILDS";
export const SUCCESS_GUILDS = "SUCCESS_GUILDS";

// GUILD
export const GET_GUILD = "GET_GUILD";
export const SUCCESS_GUILD = "SUCCESS_GUILD";

// QUESTIONS
export const GET_QUESTIONS = "GET_QUESTIONS";
export const SUCCESS_QUESTIONS = "SUCCESS_QUESTIONS";

// ANSWERS
export const GET_ANSWERS = "GET_ANSWERS";
export const SUCCESS_ANSWERS = "SUCCESS_ANSWERS";
